# Generated by Django 4.2.1 on 2023-06-27 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Male"), (1, "Female")], default=0
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("posts_amount", models.IntegerField(default=0)),
                ("followers_amount", models.IntegerField(default=0)),
                ("following_amount", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
