version: '3.8'

services:
  instagram_drf:
      build: .
      container_name: instagram_drf
      ports:
        - "8000:8000"
      command: poetry run python manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
        - redis
  celery:
      build: .
      container_name: celery
      command: poetry run celery -A core worker -l info --pool=solo
      depends_on:
        - instagram_drf
        - redis
  redis:
    image : "redis:alpine"
  db:
    image: postgres:12
    container_name: db
    env_file:
      - .env
