# Generated by Django 4.2.1 on 2023-07-24 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_actions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followmodel",
            name="followed_user_id",
        ),
    ]
